---
- hosts: localhost
  gather_facts: no
  collections:
    - community.kubernetes
    - operator_sdk.util
  tasks:
    - name: refresh inventory with running pods
      vars:
        field_selectors:
          - status.phase=Running
      import_role:
        name: "m4e"
        tasks_from: inventory.yml

- hosts: php_fpm
  gather_facts: no
  collections:
    - community.kubernetes
    - operator_sdk.util
  tasks:
    - name: import task to keep in sync moodle config
      import_role:
        name: "m4e"
        tasks_from: sync_config.yml
