---
# nginx
nginx_size: 1
nginx_image: quay.io/krestomatio/moodle_web
nginx_state: "{{ state }}"
nginx_appname: "{{ meta.name }}-nginx"
nginx_service: "{{ nginx_appname }}-service"
nginx_deploy: "{{ nginx_appname }}-deploy"
nginx_route: "{{ nginx_appname }}-route"
nginx_ingress: "{{ nginx_appname }}-ingress"
nginx_port: 8080
nginx_args: "['nginx', '-g', 'daemon off;']"
nginx_readiness_probe: true
nginx_readiness_command: "['/usr/libexec/check-container-nginx', '-r']"
nginx_readiness_initial: 5
nginx_readiness_period: 30
nginx_readiness_timeout: 3
nginx_readiness_success: 1
nginx_readiness_failure: 6
nginx_liveness_probe: true
nginx_liveness_command: "['/usr/libexec/check-container-nginx', '-l']"
nginx_liveness_initial: 5
nginx_liveness_period: 10
nginx_liveness_timeout: 3
nginx_liveness_success: 1
nginx_liveness_failure: 3
nginx_resource_requests: true
nginx_resource_requests_cpu: 200m
nginx_resource_requests_memory: 256Mi
nginx_resource_limits: true
nginx_resource_limits_cpu: 1
nginx_resource_limits_memory: 1Gi
nginx_term_grace_period: 30
nginx_route_annotations: |
  haproxy.router.openshift.io/rate-limit-connections: 'true'
  haproxy.router.openshift.io/rate-limit-connections.concurrent-tcp: '100'
  haproxy.router.openshift.io/rate-limit-connections.rate-http: '100'
  haproxy.router.openshift.io/rate-limit-connections.rate-tcp: '100'
nginx_route_spec: |
  host: {{ moodle_uri }}
  to:
    kind: Service
    name: '{{ nginx_service }}'
    weight: 100
  port:
    targetPort: http
  {% if expose_tls %}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  {% endif %}
  wildcardPolicy: None
nginx_ingress_spec: |
  rules:
  - host: '{{ moodle_uri }}'
    http:
      paths:
      - path: /
        backend:
          serviceName: '{{ nginx_service }}'
          servicePort: {{ nginx_port }}
nginx_service_spec: |
  sessionAffinity: ClientIP
  ports:
  - name: http
    port: {{ nginx_port }}
    protocol: TCP
    targetPort: {{ nginx_port }}
  selector:
    app: '{{ nginx_appname }}'
