- name: postgres secret resource definition
  vars:
    k8s_kind: Secret
    k8s_state: "{{ postgres_secret_state | default(postgres_state) }}"
    template: "{{ secret_template }}"
    metadata_name: "{{ postgres_secret }}"
    secret_data: "{{ postgres_secret_data }}"
  import_tasks: k8s/object.yml

- name: save postgres secret resource definition task
  set_fact:
    k8s_postgres_secret: "{{ k8s_object_task }}"
