# permissions for end users to view m4es.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: m4e-viewer-role
rules:
- apiGroups:
  - m4e.krestomat.io
  resources:
  - m4es
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - m4e.krestomat.io
  resources:
  - m4es/status
  verbs:
  - get
