apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: m4es.m4e.krestomatio.com
spec:
  group: m4e.krestomatio.com
  names:
    kind: M4e
    listKind: M4eList
    plural: m4es
    singular: m4e
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
