- name: set successful status
  import_tasks: k8s/status.yml
  vars:
    k8s_status_status:
      ready: "True"
    k8s_status_conditions:
      - type: "Ready"
        status: "True"
        reason: "Successful"
        message: "All tasks completed successfully"
