- name: set instantiated init status
  when: get_instantiated_condition is not defined or
        instantiated_condition is defined and not instantiated_condition
  set_fact:
    set_instantiated_status: "False"
    set_instantiated_reason: "NotInstantiated"
    set_instantiated_message: "Database has not been instantiated"

- name: set instantiated status
  when: instantiated_condition is defined and instantiated_condition
  set_fact:
    set_instantiated_status: "True"
    set_instantiated_reason: "Instantiated"
    set_instantiated_message: "Database has been instantiated"

- name: set instantiated condition fact
  vars:
    set_instantiated_status: "{{ get_instantiated_condition.status | default('Unknown') }}"
    set_instantiated_reason: "{{ get_instantiated_condition.reason | default('ReasonUnknown') }}"
    set_instantiated_message: "{{ get_instantiated_condition.message | default('Reason unknown') }}"
  when: get_instantiated_condition is not defined or
        get_instantiated_condition.status | lower != set_instantiated_status | lower or
        get_instantiated_condition.reason != set_instantiated_reason or
        get_instantiated_condition.message != set_instantiated_message
  register: set_instantiated_condition_task
  set_fact:
    set_instantiated_condition:
      - type: "Instantiated"
        status: "{{ set_instantiated_status }}"
        reason: "{{ set_instantiated_reason  }}"
        message: "{{ set_instantiated_message }}"
        lastTransitionTime: "{{ lookup('pipe', 'date --iso-8601=seconds') }}"
