- name: set ready init status
  when: get_ready_condition is not defined
  set_fact:
    set_ready_status: "False"
    set_ready_reason: "Init"
    set_ready_message: "Initiating tasks"

- name: set not instantiated status
  when: instantiated_condition is defined and not instantiated_condition
  set_fact:
    set_ready_status: "False"
    set_ready_reason: "NotInstantiated"
    set_ready_message: "Database has not been instantiated"

- name: set instantiated status
  when: instantiated_condition is defined and instantiated_condition
  set_fact:
    set_ready_status: "False"
    set_ready_reason: "Instantiated"
    set_ready_message: "Database has been instantiated"

- name: set successful status
  when: successful_condition is defined and successful_condition
  set_fact:
    set_ready_status: "True"
    set_ready_reason: "Successful"
    set_ready_message: "All tasks completed successfully"

- name: set error status
  when: error_condition is defined and error_condition
  set_fact:
    set_ready_status: "False"
    set_ready_reason: "Error"
    set_ready_message: "There was an error before completing all tasks"

- name: set ready condition fact
  vars:
    set_ready_status: "{{ get_ready_condition.status | default('Unknown') }}"
    set_ready_reason: "{{ get_ready_condition.reason | default('ReasonUnknown') }}"
    set_ready_message: "{{ get_ready_condition.message | default('Reason unknown') }}"
  when: get_ready_condition is not defined or
        get_ready_condition.status | lower != set_ready_status | lower or
        get_ready_condition.reason != set_ready_reason or
        get_ready_condition.message != set_ready_message
  register: set_ready_condition_task
  set_fact:
    set_ready_condition:
      - type: "Ready"
        status: "{{ set_ready_status }}"
        reason: "{{ set_ready_reason  }}"
        message: "{{ set_ready_message }}"
        lastTransitionTime: "{{ lookup('pipe', 'date --iso-8601=seconds') }}"
