---
dependency:
  name: galaxy
driver:
  name: delegated
lint: |
  set -e
  yamllint -d "{extends: relaxed, rules: {line-length: {max: 120}}}" .
platforms:
- name: cluster
  groups:
  - k8s
provisioner:
  name: ansible
  lint: |
    set -e
    ansible-lint
  inventory:
    group_vars:
      all:
        namespace: ${TEST_OPERATOR_NAMESPACE:-osdk-test}
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
        deploy_dir: ${MOLECULE_PROJECT_DIRECTORY}/deploy
        template_dir: ${MOLECULE_PROJECT_DIRECTORY}/molecule/templates
        operator_image: ${OPERATOR_IMAGE:-"image-registry.openshift-image-registry.svc:5000/osdk-test/m4e-operator"}
        operator_pull_policy: ${OPERATOR_PULL_POLICY:-"Always"}
        cr_template: ${CR_TEMPLATE:-"m4e_cr.yaml.j2"}
  env:
    K8S_AUTH_KUBECONFIG: ${KUBECONFIG:-"~/.kube/config"}
verifier:
  name: ansible
  lint: |
    set -e
    ansible-lint
