---
# This is an example playbook to execute Ansible tests.
- name: Verify
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - community.kubernetes

  vars:
    cr_file: "m4e.krestomatio.com_v1alpha1_m4e_cr.yaml"
    custom_resource: "{{ lookup('template', '/'.join([deploy_dir, 'crds/' + cr_file])) | from_yaml }}"

  tasks:
    - name: Create the m4e.krestomatio.com/v1alpha1.M4e and wait for reconciliation to complete
      k8s:
        state: present
        namespace: '{{ namespace }}'
        definition: '{{ custom_resource }}'
        wait: yes
        wait_timeout: 300
        wait_condition:
          type: Running
          reason: Successful
          status: "True"

    - name: Get Pods
      k8s_info:
        api_version: v1
        kind: Pod
        namespace: '{{ namespace }}'
      register: pods

    - name: Example assertion
      assert:
        that: (pods | length) > 0
