- name: k8s resources
  hosts: localhost
  gather_facts: false
  collections:
    - community.kubernetes
    - operator_sdk.util
  tasks:
    - import_role:
        name: krestomatio.k8s.v1alpha1.m4e.m4e

- name: moodle routines
  hosts: "{{ pods_ready_group }}:&{{ moodle_container_group }}"
  gather_facts: false
  collections:
    - community.kubernetes
    - operator_sdk.util
  tasks:
    - name: import moodle routines
      when: "moodle_state == 'present'"
      import_role:
        name: krestomatio.k8s.v1alpha1.m4e.m4e
        tasks_from: moodle-routines.yml
