- name: k8s resources
  hosts: localhost
  gather_facts: false
  collections:
    - community.kubernetes
    - operator_sdk.util
  tasks:
    - import_role:
        name: "m4e"

- name: php routines
  hosts: "{{ pods_ready_group }}:&{{ php_fpm_container_group }}"
  run_once: true
  gather_facts: false
  collections:
    - community.kubernetes
    - operator_sdk.util
  tasks:
    - name: include routines
      import_role:
        name: "m4e"
        tasks_from: php-routines.yml
