apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/krestomatio/jx3-pipeline-catalog/master/tasks/git-clone/git-clone.yaml
  name: release
spec:
  pipelineSpec:
    params:
    - default: master
      description: git revision to checkout (branch, tag, sha, ref…)
      name: revision
      type: string
    tasks:
    - name: from-build-pack
      params:
      - name: revision
        value: $(params.revision)
      resources: {}
      taskSpec:
        metadata: {}
        params:
        - default: master
          description: git revision to checkout (branch, tag, sha, ref…)
          name: revision
          type: string
        stepTemplate:
          env:
          - name: PIPELINE_KIND
            value: release
          - name: JX_BATCH_MODE
            value: "true"
          - name: UPDATE_VERSION
            value: Makefile
          - name: PROJECT_TIMESTAMP
            value: midnight
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - args:
          - release
          command:
          - make
          image: quay.io/krestomatio/ansible-operator-ci
          name: test
          workingDir: /workspace/source
  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
