---
- name: httpd resource definitions
  vars:
    name: httpd
    k8s_state: "{{ httpd_state }}"
    component: httpd
    metadata_app: "{{ httpd_appname }}"
  block:
  - name: httpd service resource definition
    vars:
      kind: Service
      k8s_state: "{{ httpd_pvc_state | default(httpd_state) }}"
      template: "{{ service_template }}"
      metadata_name: "{{ httpd_service }}"
      service_spec: "{{ httpd_service_spec }}"
    import_tasks: k8s.yml

  - name: set httpd deploy spec
    when: httpd_deploy_spec is not defined
    set_fact:
      httpd_deploy_spec: "{{ lookup('template', httpd_deploy_spec_template) }}"

  - name: httpd deploy resource definition
    vars:
      kind: Deployment
      k8s_state: "{{ httpd_deploy_state | default(httpd_state) }}"
      template: "{{ deploy_template }}"
      metadata_name: "{{ httpd_deploy }}"
      deploy_spec: "{{ httpd_deploy_spec }}"
    import_tasks: k8s.yml

  - name: httpd route resource definition
    when:
    - expose_type is defined and expose_type
    - "(expose_type | lower) == 'route'"
    vars:
      kind: Route
      k8s_state: "{{ httpd_route_state | default(httpd_state) }}"
      template: "{{ route_template }}"
      metadata_name: "{{ httpd_route }}"
      annotations: "{{ httpd_route_annotations | default(false) }}"
      route_spec: "{{ httpd_route_spec }}"
    import_tasks: k8s.yml

  - name: httpd route resource definition
    when:
    - expose_type is defined and expose_type
    - "(expose_type | lower) == 'ingress'"
    vars:
      kind: Ingress
      k8s_state: "{{ httpd_ingress_state | default(httpd_state) }}"
      template: "{{ ingress_template }}"
      metadata_name: "{{ httpd_ingress }}"
      annotations: "{{ httpd_ingress_annotations | default(false) }}"
      ingress_spec: "{{ httpd_ingress_spec }}"
    import_tasks: k8s.yml
