- name: set moodle new instance job spec
  when: moodle_new_instance_job_spec is not defined
  vars:
    metadata_name: "{{ moodle_new_instance_job }}"
    metadata_app: "{{ php_fpm_appname }}"
  set_fact:
    moodle_new_instance_job_spec:
      "{{ lookup('template', moodle_new_instance_job_spec_template) }}"

- name: moodle new instance job resource definition
  vars:
    kind: Job
    k8s_state: "{{ moodle_new_instance_job_state | default(php_fpm_state) }}"
    k8s_wait: true
    k8s_wait_timeout: 180
    k8s_wait_condition:
      type: "Complete"
      status: "True"
    template: "{{ job_template }}"
    metadata_name: "{{ moodle_new_instance_job }}"
    metadata_app: "{{ php_fpm_appname }}"
    job_spec: "{{ moodle_new_instance_job_spec }}"
  import_tasks: k8s.yml
