---
# tasks file for m4e
- name: import tasks
  block:
    - name: handle status
      import_tasks: status/main.yml

    - name: handle postgres
      import_tasks: postgres.yml

    - name: handle moodle
      import_tasks: moodle.yml

    - name: handle php-fpm
      import_tasks: php-fpm.yml

    - name: handle nginx
      import_tasks: nginx.yml

    - name: set successful status fact
      when: successful_condition is not defined
      set_fact:
        successful_condition: true
  rescue:
    - name: set error status fact
      set_fact:
        error_condition: true
  always:
    - name: handle status
      import_tasks: status/main.yml
