---
- name: nginx resource definitions
  vars:
    name: nginx
    k8s_state: "{{ nginx_state }}"
    component: nginx
    metadata_app: "{{ nginx_appname }}"
  block:
    - import_tasks: nginx/deploy.yml

    - import_tasks: nginx/service.yml

    - import_tasks: nginx/route.yml

    - import_tasks: nginx/ingress.yml
