---
- name: postgres resource definitions
  vars:
    name: postgres
    k8s_state: "{{ postgres_state }}"
    component: postgres
    metadata_app: "{{ postgres_appname }}"
  block:
    - import_tasks: postgres/pvc.yml

    - import_tasks: postgres/secret.yml

    - import_tasks: postgres/deploy.yml

    - import_tasks: postgres/service.yml
